prevent:
  # prevent moving into unloaded chunks
  moving-into-unloaded-chunks: true
  # prevent chicken egg hatch spawn
  egg-hatch: false
  # prevent block drops on creative
  creative-block-drops: false
  # prevent redstone
  redstone: false
  # prevent fire spread
  fire-spread: true
  trample:
    # prevent player trample
    FARMLAND: true
    TURTLE_EGG: true
  explode:
    # prevent entity block damage
    CREEPER: true
    WITHER_SKULL: true
    DRAGON_FIREBALL: true
  change-block:
    # prevent entity change block
    SHEEP: true
    ENDERMAN: true
    WITHER: true
    ENDER_DRAGON: true
  spawn:
    # prevent entity spawn
    PHANTOM: true
  entity-target:
    # prevent entity target
    ZOMBIE:
      VILLAGER: true
    DROWNED:
      VILLAGER: true
    HUSK:
      VILLAGER: true
  block-form:
    # prevent block form
    SNOWMAN: true
projectile-launch:
  # removes projectile after launch, 0 to disable, 20 is 1 sec
  PLAYER:
    cancel-on-hit: true
    remove-on-hit-if-creative: true
    SNOWBALL: 100
    ARROW: 600
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 100
    TRIDENT: 0
  SKELETON:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 100
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
  STRAY:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 100
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
  PILLAGER:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 100
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
  DROWNED:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 0
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 100
  SNOWMAN:
    cancel-on-hit: true
    SNOWBALL: 100
    ARROW: 0
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
