prevent:
  moving-into-unloaded-chunks: true
  trample:
    # trampling
    FARMLAND: true
    TURTLE_EGG: true
  explode:
    # entity explode
    CREEPER: true
    # just-in-case
    WITHER_SKULL: true
    # just-in-case
    DRAGON_FIREBALL: true
  change-block:
    # sheep changes grass block to dirt
    SHEEP: true
    # enderman block pick up
    ENDERMAN: true
    # just-in-case
    CREEPER: true
    # just-in-case
    ENDER_DRAGON: true
    # just-in-case
    DRAGON_FIREBALL: true
    # just-in-case
    WITHER: true
    # just-in-case
    WITHER_SKULL: true
  spawn:
    # entity spawn
    PHANTOM: true
  entity-target:
    # entity target
    ZOMBIE:
      VILLAGER: true
    DROWNED:
      VILLAGER: true
    HUSK:
      VILLAGER: true
  block-form:
    # snowman trails
    SNOWMAN: true
projectile-launch:
  # removes projectile after launch, 0 to disable, 20 is 1 sec
  PLAYER:
    cancel-on-hit: true
    remove-on-hit-if-creative: true
    SNOWBALL: 100
    ARROW: 600
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 100
    TRIDENT: 0
  SKELETON:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 100
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
  STRAY:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 100
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
  PILLAGER:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 100
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
  DROWNED:
    cancel-on-hit: false
    SNOWBALL: 0
    ARROW: 0
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 100
  SNOWMAN:
    cancel-on-hit: true
    SNOWBALL: 100
    ARROW: 0
    SPECTRAL_ARROW: 0
    SPLASH_POTION: 0
    TRIDENT: 0
